### ISSUE TITLE
Clarity Exception preventing parsing a new replay

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#113]
I came across a replay that threw an exception that I haven't seen before. The replay ID that's causing this exception is 2779160650, and I'll add the full exception message below. The code I have tested this on is basically a ControllableRunner that does nothing but seek to the next tick until the last tick and then halts.

What I've noticed is that the replay itself ends at tick 53349 but the parse breaks at tick 33138. I've tried jumping past to a later tick in the replay but it still broke each time.

Error Message:
```
Exception in thread "clarity-runner" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
	at skadistats.clarity.processor.runner.ControllableRunner.access$1401(ControllableRunner.java:13)
	at skadistats.clarity.processor.runner.ControllableRunner$3.run(ControllableRunner.java:208)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:170)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 4 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at skadistats.clarity.wire.Packet.parse(Packet.java:36)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:246)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at skadistats.clarity.wire.Packet.parse(Packet.java:34)
	... 10 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at skadistats.clarity.wire.common.proto.NetMessages$CSVCMsg_PacketEntities.<init>(NetMessages.java:11288)
	at skadistats.clarity.wire.common.proto.NetMessages$CSVCMsg_PacketEntities.<init>(NetMessages.java:11251)
	at skadistats.clarity.wire.common.proto.NetMessages$CSVCMsg_PacketEntities$1.parsePartialFrom(NetMessages.java:11380)
	at skadistats.clarity.wire.common.proto.NetMessages$CSVCMsg_PacketEntities$1.parsePartialFrom(NetMessages.java:11375)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:104)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:124)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:129)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at skadistats.clarity.wire.common.proto.NetMessages$CSVCMsg_PacketEntities.parseFrom(NetMessages.java:11659)
	... 14 more
```

**Comment by spheenik** [comment]
It's a corrupt replay. I played it back in the real client, and it stops reading it as well with a "message parse error".

**Comment by TodorovicF** [comment]
That's what I thought too, thanks! Do you know if there's any way to tell so I can prevent my code from attempting to parse it in the first place?

**Comment by spheenik** [comment]
Nope, there's no checksums whatsoever. You will only find out when you start to parse the defective message...
