### ISSUE TITLE
Support dota2 7.00?

### ISSUE THREAD

**Issue by acala127** [skadistats/clarity#119]
Now dota2 7.00 is out, any plan to support new format? Thanks.

**Comment by spheenik** [comment]
I have tested a console recorded replay yesterday, which worked out of the box.

I still have to update the protobufs, there's slight changes in them here and there. I'll do it sometime this week.

**Comment by acala127** [comment]
Thanks you very much!
好人一生平安

**Comment by TimotheeJeannin** [comment]
Hi ! It would be great to have the protobufs updated. Our service (dotamemories.com) is down right now. Is there anything I can do to help ?

**Comment by spheenik** [comment]
This should not be because of the protobufs. What is your error?

**Comment by TimotheeJeannin** [comment]
I have this error : 

    Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: entity at index 4023 was not found for update.
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
        at com.dotamemories.Main.run(Main.java:33)
        at com.dotamemories.Main.main(Main.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: entity at index 4023 was not found for update.
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:170)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 8 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: entity at index 4023 was not found for update.
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:248)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 11 more
    Caused by: java.lang.RuntimeException: entity at index 4023 was not found for update.
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:167)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 14 more

**Comment by spheenik** [comment]
Ok, this is unrelated to the protobufs.
What version of clarity are you using? 2.1?

**Comment by TimotheeJeannin** [comment]
Yes I use clarity 2.1. Maybe it's an error on my side ?

**Comment by spheenik** [comment]
I don't think it's an error on your side. Could you try another replay to rule out corrupt data?

**Comment by spheenik** [comment]
Ok, seems like there's a new data type in the replay that clarity is not aware of, which makes it assume int, and then strangulate itself. I'll see that I fix it asap.

**Comment by TimotheeJeannin** [comment]
I checked with some other replays : 

- 2842017392.dem Working Fine
- 2842157772.dem Error
- 2842221352.dem Error
- 2842270110.dem Working Fine

Thank you for your support !

**Comment by spheenik** [comment]
I just pushed a new snapshot of clarity 2.2
Are you able to check if it fixes this? There should not be any incompatibilities against 2.1.

**Comment by spheenik** [comment]
there's now also a 2.1.1-SNAPSHOT which has the fix. Please try it and report back!

**Comment by TimotheeJeannin** [comment]
Just checked with a few replays and it appears to be working. Thank you very much !

**Comment by TimotheeJeannin** [comment]
I will try the fix and production and will tell you if it is working for a large amount of replays.

**Comment by TimotheeJeannin** [comment]
Hi @spheenik,

I parsed a large number of replays with the version **2.1.1-SNAPSHOT* *and it seems to be working fine except for a few matches.

While trying to parse matches `2843744176` and `2843584137` I came across this error :

    Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
            at skadistats.clarity.event.Event.raise(Event.java:25)
            at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
            at com.dotamemories.Main.run(Main.java:33)
            at com.dotamemories.Main.main(Main.java:70)
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
            at skadistats.clarity.event.Event.raise(Event.java:25)
            at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:170)
            at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
            at skadistats.clarity.event.Event.raise(Event.java:23)
            ... 3 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
            at skadistats.clarity.event.Event.raise(Event.java:25)
            at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:248)
            at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
            at skadistats.clarity.event.Event.raise(Event.java:23)
            ... 6 more
    Caused by: java.lang.RuntimeException: java.lang.NullPointerException
            at skadistats.clarity.event.Event.raise(Event.java:25)
            at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:159)
            at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
            at skadistats.clarity.event.Event.raise(Event.java:23)
            ... 9 more
    Caused by: java.lang.NullPointerException
            at skadistats.clarity.decoder.s2.Serializer.getValueForFieldPath(Serializer.java:70)
            at skadistats.clarity.decoder.s2.S2DTClass.getValueForFieldPath(S2DTClass.java:74)
            at skadistats.clarity.model.Entity.getPropertyForFieldPath(Entity.java:84)
            at com.dotamemories.processor.ItemProcessor.onItemCreated(ItemProcessor.java:113)
            at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
            at skadistats.clarity.event.Event.raise(Event.java:23)
            ... 12 more

Is it something wrong with my code ?

**Comment by spheenik** [comment]
Nope. Not your code. I will have a look soon.

**Comment by spheenik** [comment]
Ok I had a look onto both replays, and I have to revert my statement from yesterday. It's something with your code. ItemProcessor.onItemCreated() seems to look up a property that is not existing in the data.

**Comment by TimotheeJeannin** [comment]
I found the issue. 
Thank you for your time and great work on the parser !

**Comment by spheenik** [comment]
You're welcome ;-)

**Comment by jiricapek** [comment]
Hi,
I am using Gradle and central maven repository (https://mvnrepository.com/artifact/com.skadistats/clarity) for dependency management and there is no version 2.1.1 or 2.2. Would it be possible to build/updated this central maven repository ? I am getting similar bug as above. I guess that sonatype plugin should somehow handle that.

**Comment by spheenik** [comment]
There is only a 2.1.1-SNAPSHOT, which is available via the sonatype snapshot repository. I have no clue how to get that with gradle, but it certainly is possible.

But: Since no one complained any more for a week now, I just made the formal 2.1.1 release, which should be up on Maven Central in a couple of minutes.

**Comment by jiricapek** [comment]
Hi,
I know how to get it with gradle ;). Just need it in central since it is there it works. It does not display yet, but it is possible to get it and it works. Thanks !
