### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity#137]
I ran into the following exception:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:90)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onUpdateStringTable(S2StringTableEmitter.java:67)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:85)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:85)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:85)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
```

If a replay is needed to debug this, I can send one to you.

**Comment by spheenik** [comment]
Send it.

**Comment by ykim** [comment]
@spheenik : Did you receive the replay? Let me know if there's anything I can do to help

**Comment by spheenik** [comment]
Yes, I have it, but I had other things to do.

**Comment by spheenik** [comment]
@invokr: Seltsamer Bug, kannst du mal schauen, ob butterfly auch drüberfällt?

**Comment by spheenik** [comment]
@ykim: I can reproduce, but I am unsure whether it's corrupt data or a bug. Have you had the bug only with this one replay?

**Comment by invokr** [comment]
@spheenik Brauch dann schon das replay zum testen ;)

**Comment by spheenik** [comment]
Seems to be a bug, I am gonna have to do some detective work...

**Comment by ykim** [comment]
Let me know if there's something you need on my end. I'll be on the lookout for any other replays that gets borked with the same issue.

**Comment by ykim** [comment]
I have another replay with the same issue. Do you want me to send it your way again?

**Comment by spheenik** [comment]
Wtf. I replied via email 2 days ago, but it didn't show up here. 

Sure, send it!

**Comment by ykim** [comment]
I sent it yesterday. Let me know if there's anything else you need! :)

**Comment by STRATZ-Ken** [comment]
I have more than enough errors for this.  Started after I added the following code.

public void onModifierEntry(Context ctx, DotaModifiers.CDOTAModifierBuffTableEntry mod) {
        Entities entities = ctx.getProcessor(Entities.class);
        Entity caster = entities.getByHandle(mod.getCaster());
}

Ids where it occurs : 
3097930791 
3097831349 
3097879573 
3097882766 
3097791651 
 3097879990 
3097854204 

I can give more Ids if you need them, I have thousands.

**Comment by spheenik** [comment]
Heads up: Just pushed a new snapshot which works around the issue. I am still unsure what Valve changed, and I have to dig deeper to solve this. Notice that it won't work for 3066062405, but it's a start.

**Comment by invokr** [comment]
@spheenik Is the bug Ken mentions still the same one we talked about a while back, were the index specified in the cyclic buffer has not been written to yet? Or is this a new thing?

You can just copy my wrap-around code in any case.

**Comment by spheenik** [comment]
@invokr: Yes it is, but it seems more difficult than that. Your code might not crash, but it still produces invalid keys. We have to find out what exactly valve changed.

**Comment by invokr** [comment]
Do you have a good accurate description of what's exactly happening? Can you mail me the id of a valid replay where this happens?

We can just ask Ben to ask someone at Valve what they changed.

**Comment by spheenik** [comment]
kurz TS?

**Comment by ykim** [comment]
@spheenik : Was this figured out?

**Comment by spheenik** [comment]
It was worked around, and it only happened on game end. Do you still have problems?

**Comment by ykim** [comment]
I don't, but I was wondering why this wasn't closed yet xD

**Comment by spheenik** [comment]
Could close, but maybe sometime this or next life I might find the real fix instead of a shitty workaround :)
