### ISSUE TITLE
Hi, which program shall I use to run this?

### ISSUE THREAD

**Issue by k5dash** [skadistats/clarity#143]
I used different version of eclipse but seems this project is not compatible of these.
Can you give me a guidance?

Thanks, sincerely

**Comment by spheenik** [comment]
You have to be more specific on what your problem is!

**Comment by k5dash** [comment]
Exception in thread "main" skadistats.clarity.ClarityException: oops. no provider found for required usage point interface skadistats.clarity.processor.reader.OnMessage
	at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:123)
	at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:135)
	at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:79)
	at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:49)
	at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:29)
	at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:35)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:37)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at skadistats.clarity.examples.allchat.AllChatProcessor.main(AllChatProcessor.java:23)

**Comment by k5dash** [comment]
I am trying to run the easiest one which is AllChatProcessor, looks very similar to the go version "manta". However I got this errors, is there something I am missing? I just simply click the AllChatProcessor and run as Java application ( replaced the file name with my own replay)
