### ISSUE TITLE
skadistats.clarity.ClarityException: oops. no provider found for required 

### ISSUE THREAD

**Issue by k5dash** [skadistats/clarity#145]
I am trying to run the easiest one which is AllChatProcessor, looks very similar to the go version "manta". However I got this errors, is there something I am missing? I just simply click the AllChatProcessor and run as Java application ( replaced the file name with my own replay)

Exception in thread "main" skadistats.clarity.ClarityException: oops. no provider found for required usage point interface skadistats.clarity.processor.reader.OnMessage
at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:123)
at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:135)
at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:79)
at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:49)
at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:29)
at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:35)
at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:37)
at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
at skadistats.clarity.examples.allchat.AllChatProcessor.main(AllChatProcessor.java:23)

**Comment by k5dash** [comment]
Hmm I get it running. However the data I got is a bit different from what I expected.
I expected the hero position will be -7500,-7500 to 7500, 7500 and 0,0 will be in the middle of the map.
because I used to write script for dota2.

However CBodyComponent.m_cellX and CBodyComponent.m_cellY are integers around 128.
which is pretty not accurate. am I missing something here?

**Comment by spheenik** [comment]
Here is some example code which shows positions: https://github.com/spheenik/clarity-analyzer/blob/master/src/main/java/skadistats/clarity/analyzer/main/icon/EntityIcon.java#L38-L60
