### ISSUE TITLE
java.io.EOFException on live game

### ISSUE THREAD

**Issue by ect1** [skadistats/clarity#147]
I was trying to load an auto-replay on running game
1. create lobby with localhost server
2. loaded at tick clarity example 

Exception in thread "main" skadistats.clarity.processor.runner.ControllableRunner$4: Runner thread was terminated by an exception
	at skadistats.clarity.processor.runner.ControllableRunner.waitForTickReached(ControllableRunner.java:239)
	at skadistats.clarity.processor.runner.ControllableRunner.tick(ControllableRunner.java:273)
	at skadistats.clarity.examples.tick.Main.runControlled(Main.java:59)
	at skadistats.clarity.examples.tick.Main.main(Main.java:68)
Caused by: java.io.EOFException
	at skadistats.clarity.source.MappedFileSource.readBytes(MappedFileSource.java:50)
	at skadistats.clarity.processor.reader.InputSourceProcessor.readPacket(InputSourceProcessor.java:94)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:180)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.ControllableRunner$3.run(ControllableRunner.java:197)
	at java.lang.Thread.run(Thread.java:745)

**Comment by spheenik** [comment]
What exactly are you trying to read? A replay file that is written as the game plays?

**Comment by spheenik** [comment]
If so, you'd have to provide your custom implementation of the [Source](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/Source.java) class, which would block until new content in the file is available. My guess is you cannot use a MappedFileSource since it cannot accomodate for bytes written to the file after it was opened.

**Comment by ect1** [comment]
Yeah that's was exactly what I did. Unfortunately, I have no luck or not good same as you. I think you should add some enhancement for this api for reading a file for a live game. This is good especially for private game because right now valve cant private api yet to grab match details live on private match/lobby.

**Comment by spheenik** [comment]
Can you provide the source of what you've got?

**Comment by STRATZ-Ken** [comment]
I agree, @ect1 We would love to take this further if possible.

**Comment by spheenik** [comment]
I know a place where code that does this already exists. If they agree I can add it, or at least have a look at how difficult it would be..

**Comment by ect1** [comment]
I tried to play in private game and record using console then I inspect the generated .dem file using Clarity analyser. I was able to see classes but the file won't able see it if I don't refresh the replay folder. 
The .dem file stops feeding data after 15 or 30 mins while playing even refresh the folder over and over, but will complete file after the game is ended or leaving the game.

**Comment by spheenik** [comment]
Clarity Analyzer uses the MappedFileSource, which I suppose is unable to detect changes to the file after initial mapping into memory. One could adapt it to use a source which can do this.

Another thing that one of my clients has is that the dota client indeed randomly stops updating the file after a while (most probably a bug). In this case the only way to fix this is restarting the client, which seems to be no real option when you're the one playing...

**Comment by ect1** [comment]
Hi, I also tested to use WatchService to watch replay folder and It won't sees any changes unless I clicked F5 or refresh the replay folder.

**Comment by spheenik** [comment]
I managed to put some time into this, and came up with [this gem](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/LiveSource.java).

It's pretty well tested already, and I made clarity-analyzer use it as well.

Please test!

**Comment by ect1** [comment]
I got `Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: skadistats.clarity.source.LiveSource$TimeoutException: timeout while waiting for data
        at skadistats.clarity.source.LiveSource.blockUntilDataAvailable(LiveSource.java:288)
        at skadistats.clarity.source.LiveSource.readBytes(LiveSource.java:99)
        at skadistats.clarity.processor.reader.InputSourceProcessor.readPacket(InputSourceProcessor.java:97)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:187)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
        at skadistats.clarity.examples.combatlog.Main.run(Main.java:159)
        at skadistats.clarity.examples.combatlog.Main.main(Main.java:165)
        ... 6 more`

here's is the steps
1. record using console.
2. change code is combatlog with
`new SimpleRunner(new LiveSource(a, 10, TimeUnit.SECONDS)).runWith(this);`

**Comment by spheenik** [comment]
Seems like the replay was not updated for 10 seconds. Can you up the timeout?

**Comment by ect1** [comment]
got same exception at 120 sec

**Comment by spheenik** [comment]
What operating system are you on?

**Comment by ect1** [comment]
win 7

**Comment by spheenik** [comment]
Might be that the OS does not properly support the watch service.
Quick googling revealed [this](https://stackoverflow.com/a/33760546/1856400).

I have not yet had the opportunity to test this on Win 7. 

Can you try to patch the LiveSource to do a `outputFile.length()` every second and see if that helps?

**Comment by STRATZ-Ken** [comment]
Started testing the test case you created.

Getting : 

```
java.lang.NoClassDefFoundError: skadistats/clarity/wire/common/proto/Demo$CDemoStop
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at skadistats.clarity.processor.runner.ExecutionModel.findUsagePoints(ExecutionModel.java:155)
	at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:74)
	at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:48)
	at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:37)
	at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:28)
	at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:43)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:37)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at Worker.demoLiveSource(Worker.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: skadistats.clarity.wire.common.proto.Demo$CDemoStop
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more

```

**Comment by STRATZ-Ken** [comment]
So I got it running.  I am also getting a Timeout on Windows 10.  

```
skadistats.clarity.source.LiveSource$TimeoutException: timeout while waiting for data
	at skadistats.clarity.source.LiveSource.blockUntilDataAvailable(LiveSource.java:288)
	at skadistats.clarity.source.LiveSource.readBytes(LiveSource.java:99)
	at skadistats.clarity.processor.reader.InputSourceProcessor.readPacket(InputSourceProcessor.java:97)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:187)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at Worker.demoLiveSource(Worker.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

```

**Comment by spheenik** [comment]
Damnit that sucks. I gotta test this on a windows machine soon :(

**Comment by STRATZ-Ken** [comment]
Hit me up on Steam when you get a minute.

**Comment by STRATZ-Ken** [comment]
Any update on Timeout on Windows machines?

**Comment by spheenik** [comment]
No windows machine on hand, has to wait until early next week.

**Comment by spheenik** [comment]
So there was indeed a problem with Windows machines not firing any modified events. I worked around this with [this commit](https://github.com/skadistats/clarity/commit/3e95b77c3e5f6f4258d748de7447a10a86162728), and uploaded a new snapshot. Please test.

**Comment by STRATZ-Ken** [comment]
Looks like still not working. Windows 10 x 64.  If I stop the demo and run it, works fine.  If the demo is still recording, it breaks with a timeout.

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: skadistats.clarity.source.LiveSource$TimeoutException: timeout while waiting for data
        at skadistats.clarity.source.LiveSource.blockUntilDataAvailable(LiveSource.java:305)
        at skadistats.clarity.source.LiveSource.setPosition(LiveSource.java:99)
        at skadistats.clarity.source.Source.skipBytes(Source.java:135)
        at skadistats.clarity.model.engine.AbstractDotaEngineType$1.skip(AbstractDotaEngineType.java:91)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:220)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
        at Worker.main(Worker.java:36)
        ... 5 more`

**Comment by spheenik** [comment]
Please try timeout 30+ secs, and report back.

**Comment by sosenko1995** [comment]
Could you please explain how you "record" using console? Is it a Dota2 console? What command do you use?
@ect1 @spheenik

**Comment by STRATZ-Ken** [comment]
This solved the issue. 

@spheenik Looks like as of 8/1/2018 (Update 7.19) getting some crash converting a string to int.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at skadistats.clarity.processor.entities.Entities.onBaselineEntry(Entities.java:94)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.stringtables.BaseStringTableEmitter.raise(BaseStringTableEmitter.java:77)
	at skadistats.clarity.processor.stringtables.BaseStringTableEmitter.setSingleEntry(BaseStringTableEmitter.java:73)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:143)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onUpdateStringTable(S2StringTableEmitter.java:73)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:249)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:178)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
```

Does not seem to effect anything other than streaming live games.

**Comment by STRATZ-Ken** [comment]
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: skadistats.clarity.ClarityException: entity at index 152 was not found for update.
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:178)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:37)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:251)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:37)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:178)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:37)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
        at Worker.main(Worker.java:34)`

**Comment by STRATZ-Ken** [comment]
So, unsure how to explain this but something is still not 100% working on Windows 10 machine.  Friend who is RU is trying to run the same app as me but it is failing.  Tried for about 5 hours, but have given up.

We have debugged the following.

- Start a recording, run the parser, get timeout error.  Increased timeout to 120seconds, still error.

- Using the test file method, read the file, then output to another file, then read that file. Timeout error.

- When the file is "reading" we notice that the size of the recording does not change in the Dota folder.  But if I stop reading it will then increase.  WriteLock from Dota 2?

- Take a replay that has finished, and it reads just fine.  

Works on my computer just fine, is there some type of debug we can do to help fix this?

**Comment by spheenik** [comment]
That the filesize does not increase by it's own was exactly the problem I had on Windows. I could only get it to increase by adding the [some code](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/LiveSource.java#L202-L203) to get it's filesize repeatedly, which then would update it. This is working on all Win10 machines I have access to, so I cannot really help, but I suggest you add some debug log to see if the watcher detects the change.

What underlying filesystem is the replay written to?

**Comment by spheenik** [comment]
...and also check if [the LiveSource finds the file readable at all](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/LiveSource.java#L236)
