### ISSUE TITLE
7.07 Possible Bugs

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#150]
Match Id : 3535414622  
```
skadistats.clarity.ClarityException: entity at index 9780 was not found for update.
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:135)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)

```

**Comment by STRATZ-Ken** [comment]
Match Id : 3535465473 

`skadistats.clarity.ClarityException: entity at index 9489 was not found for update.
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:135)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
`

**Comment by STRATZ-Ken** [comment]
Match Id : 3535535060 

```
skadistats.clarity.ClarityException: Baseline for class CDOTA_Unit_Hero_Oracle (598) not found.
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:189)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:126)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)

```

**Comment by STRATZ-Ken** [comment]
Match Id : 3535452320 

```
skadistats.clarity.ClarityException: Baseline for class CSun (776) not found.
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:189)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:126)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)

```

**Comment by STRATZ-Ken** [comment]
Match Id : 3535454104 

```
java.lang.ArrayIndexOutOfBoundsException: 66
	at skadistats.clarity.decoder.bitstream.NormalBitStream64.readUBitInt(NormalBitStream64.java:33)
	at skadistats.clarity.decoder.bitstream.BitStream.readUBitVar(BitStream.java:162)
	at skadistats.clarity.decoder.s2.S2FieldReader.readDeletions(S2FieldReader.java:110)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:164)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)

```

**Comment by spheenik** [comment]
Damn, I even tried a console recorded replay from the testserver yesterday, and it seemed to work fine.
I'm gonna have a look now.

**Comment by STRATZ-Ken** [comment]
Match Id : 3537474180 

```
java.io.IOException: block overrun
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.getAndMoveToFrontDecode(BZip2CompressorInputStream.java:689)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.initBlock(BZip2CompressorInputStream.java:315)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartA(BZip2CompressorInputStream.java:872)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.setupNoRandPartB(BZip2CompressorInputStream.java:921)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read0(BZip2CompressorInputStream.java:221)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream.read(BZip2CompressorInputStream.java:176)
	at skadistats.clarity.source.InputStreamSource.readBytes(InputStreamSource.java:47)
	at skadistats.clarity.processor.reader.InputSourceProcessor.readPacket(InputSourceProcessor.java:94)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:180)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at Worker$1.handleDelivery(Worker.java:153)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

This one may be less a 7.07 specific bug, but I figured I would post.

**Comment by spheenik** [comment]
@STRATZ-Ken Nothing I can do, data seems to be corrupt.

**Comment by TimotheeJeannin** [comment]
I also have some issues:

Match Id : 3538641844

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Invalid memory access: Tried to access array of length 783 at offset 792
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
        at com.dotamemories.Main.run(Main.java:33)
        at com.dotamemories.Main.main(Main.java:70)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Invalid memory access: Tried to access array of length 783 at offset 792
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:170)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Invalid memory access: Tried to access array of length 783 at offset 792
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:248)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 6 more
Caused by: java.lang.RuntimeException: Invalid memory access: Tried to access array of length 783 at offset 792
        at skadistats.clarity.decoder.bitstream.UnsafeBitStreamBase.checkAccessRelative(UnsafeBitStreamBase.java:48)
        at skadistats.clarity.decoder.bitstream.UnsafeBitStream64.readUBitInt(UnsafeBitStream64.java:30)
        at skadistats.clarity.decoder.bitstream.BitStream.readUBitVar(BitStream.java:154)
        at skadistats.clarity.decoder.s2.S2FieldReader.readDeletions(S2FieldReader.java:109)
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:204)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 9 more

```

**Comment by spheenik** [comment]
@TimotheeJeannin what version of clarity is that?

**Comment by TimotheeJeannin** [comment]
It was version 2.1.1, it works fine with 2.2-SNAPSHOT.

**Comment by Shopot742** [comment]
Match ID: 3576150500
`Caused by: skadistats.clarity.ClarityException: Baseline for class CDOTA_Unit_Hero_Ogre_Magi (598) not found.`
version 2.2-SNAPSHOT

**Comment by spheenik** [comment]
Hmm, if this is a single instance, I'd say the replay is corrupt. If you have one more, I'll have a look. Thanks!
