### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lkairies** [skadistats/clarity#152]
I ran into the following Exception:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -610771328
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:147)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.TimedRunner.runWith(TimedRunner.java:102)
	at com.dojomadness.vconsole2.client.Client.main(Client.java:425)
```

Happens with different replays, e.g. http://replay133.valve.net/570/3657247929_846611210.dem.bz2

**Comment by spheenik** [comment]
@STRATZ-Ken: Do you notice increased error rates lately?

**Comment by spheenik** [comment]
Today I took some time to look into this issue, but I cannot reproduce it anymore, not even with the exact same replay file I could reproduce the error with in January. Is anyone still experiencing this problem?

**Comment by spheenik** [comment]
Lukas: As we found out today, this is because an old version of clarity was used. Check back with Levin for details. Case closed. Cheers!
