### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#167]
I tested running clarity on an ARM processor and got an error:
```
Exception in thread "pool-1-thread-1" org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Linux and os.arch=aarch64
        at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:299)
        at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:163)
        at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:145)
        at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
        at skadistats.clarity.processor.reader.InputSourceProcessor.readPacket(InputSourceProcessor.java:96)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:180)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
        at opendota.Parse.<init>(Parse.java:174)
        at opendota.Main$MyHandler.handle(Main.java:27)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Perhaps we could upgrade the snappy dependency to resolve this issue?  It looks like support was added in 1.1.2.2:
https://github.com/xerial/snappy-java/issues/134

**Comment by howardchung** [comment]
Seems that 1.1.7.1 is incompatible with the replay, but looks like 1.1.2.6 is fine.

**Comment by spheenik** [comment]
Updated to 1.1.7.1. (2.3-SNAPSHOT)
It did not seem incompatible with the replay I had here. If you still have problems, I think it must be something else. Please test and report back with new findings.

**Comment by howardchung** [comment]
http://replay137.valve.net/570/3833080676_1296818202.dem.bz2 is the replay I tested

**Comment by spheenik** [comment]
Set version to 1.1.2.6, and uploaded a new snapshot. Plz Test.
