### ISSUE TITLE
7.20 Dota Release created this new bug.

### ISSUE THREAD

**Issue by KenBeanNet** [skadistats/clarity#186]
Mon Nov 19 13:41:45 PST 2018 | 4228331344 |  | exception | java.lang.NegativeArraySizeException
	at skadistats.clarity.decoder.s2.field.Field.ensureSubStateCapacity(Field.java:58)
	at skadistats.clarity.decoder.s2.field.VarArrayField.setValueForFieldPath(VarArrayField.java:79)
	at skadistats.clarity.decoder.s2.Serializer.setValueForFieldPath(Serializer.java:74)
	at skadistats.clarity.decoder.s2.S2DTClass.setValueForFieldPath(S2DTClass.java:78)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:77)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:12)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:139)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:261)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:188)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at Worker$1.handleDelivery(Worker.java:155)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KenBeanNet** [comment]
4228331344 is the Match Id.

**Comment by spheenik** [comment]
pushed new snapshot
