### ISSUE TITLE
Exception on getLastTick

### ISSUE THREAD

**Issue by Ptitpopcorn** [skadistats/clarity#187]
`MappedFileSource source = new MappedFileSource("replay.dem");
ControllableRunner controllableRunner = new ControllableRunner(source);
controllableRunner.seek(controllableRunner.getLastTick());`
`
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at skadistats.clarity.source.MappedFileSource.setPosition(MappedFileSource.java:42)
	at skadistats.clarity.model.engine.AbstractDotaEngineType.determineLastTick(AbstractDotaEngineType.java:35)
	at skadistats.clarity.source.Source.determineLastTick(Source.java:180)
	at skadistats.clarity.source.Source.getLastTick(Source.java:194)
	at skadistats.clarity.processor.runner.ControllableRunner.getLastTick(ControllableRunner.java:342)

Using Clarity 2.3

**Comment by spheenik** [comment]
This is fixed in 2.4-SNAPSHOT.

**Comment by Ptitpopcorn** [comment]
Thanks

**Comment by spheenik** [comment]
You're welcome! :)
