### ISSUE TITLE
CSGO info example not working + issues with OnPlayerInfo

### ISSUE THREAD

**Issue by spheenik** [skadistats/clarity#190]
The no provider found issue was fixed by setting maven not to use workspace dependencies (even though clarity should have been on master.

The info package seems to fail with the latest from master however but this might just be a dota2/csgo thing. (log file included)
[clarityTestInDos.txt](https://github.com/skadistats/clarity/files/2676909/clarityTestInDos.txt)

Perhaps this is simply due to me not understanding the interface, but when I add a
@OnPlayerInfo
public void onPlayerInfo(PlayerInfoType info) {
...
}

to the gameevent Main.java class example, I get this:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.IllegalArgumentException: bad spread array length
        at java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(Unknown Source)
        at java.lang.invoke.MethodHandle.asSpreaderChecks(Unknown Source)
        at java.lang.invoke.MethodHandle.asSpreader(Unknown Source)
        at skadistats.clarity.event.AbstractInvocationPoint.bind(AbstractInvocationPoint.java:57)
        at skadistats.clarity.processor.runner.ExecutionModel.bindInvocationPoints(ExecutionModel.java:193)
        at skadistats.clarity.processor.runner.ExecutionModel.initialize(ExecutionModel.java:289)
        at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:45)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:37)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
        at skadistats.clarity.examples.gameevent.Main.run(Main.java:29)
        at skadistats.clarity.examples.gameevent.Main.main(Main.java:35)
        ... 6 more
```
_Originally posted by @erGOD in https://github.com/skadistats/clarity/issues/58#issuecomment-447040762_

**Comment by spheenik** [comment]
@erGOD: Created new issue, as it's unrelated to unknown message types.
So here goes: The info example does not work with CSGO-replays, as you suspected, only Dota. This is because there simply is no game info in it. I should probably just error out with a clear message when someone tries this.

For the issue with `@OnPlayerInfo`, the signature of your function is bad, it should be like this:
```java
@OnPlayerInfo
public void onPlayerInfo(int entityIdx, PlayerInfoType info) {
...
}
```

**Comment by erGOD** [comment]
Thanks for the help!
