### ISSUE TITLE
Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#234]
MatchId : 5442528128 

Latest 2.5 Build.
Latest 4.22 Protos.

```
|  | exception | com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at skadistats.clarity.wire.common.proto.DotaModifiers$CDOTAModifierBuffTableEntry.<init>(DotaModifiers.java:487)
	at skadistats.clarity.wire.common.proto.DotaModifiers$CDOTAModifierBuffTableEntry.<init>(DotaModifiers.java:449)
	at skadistats.clarity.wire.common.proto.DotaModifiers$CDOTAModifierBuffTableEntry$1.parsePartialFrom(DotaModifiers.java:728)
	at skadistats.clarity.wire.common.proto.DotaModifiers$CDOTAModifierBuffTableEntry$1.parsePartialFrom(DotaModifiers.java:723)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:104)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:124)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:129)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at skadistats.clarity.wire.common.proto.DotaModifiers$CDOTAModifierBuffTableEntry.parseFrom(DotaModifiers.java:1777)
	at skadistats.clarity.processor.modifiers.Modifiers.onTableEntry(Modifiers.java:21)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.stringtables.BaseStringTableEmitter.raise(BaseStringTableEmitter.java:85)
	at skadistats.clarity.processor.stringtables.BaseStringTableEmitter.setSingleEntry(BaseStringTableEmitter.java:81)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:143)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onUpdateStringTable(S2StringTableEmitter.java:73)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:251)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:178)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by spheenik** [comment]
4.22 or 4.24?

**Comment by STRATZ-Ken** [comment]
4.22.  Which I believe was the latest from the repo?

**Comment by spheenik** [comment]
Nope, 4.24 is the latest.

**Comment by STRATZ-Ken** [comment]
I will give it a try. My bad.

**Comment by spheenik** [comment]
Might crash as well, plz test and report back.

**Comment by STRATZ-Ken** [comment]
Same, another example match id : 5442099996

**Comment by spheenik** [comment]
Ok, will look tomorrow.

**Comment by spheenik** [comment]
Ok, had a look: There seems to be a problem with the data in the string table. For replay 5442099996 it happens exactly one time. I guess there's some minor bug in the replay writing code. I added a workaround that will return you the parsed entry which contains only the data up to the point where the binary data was invalid. New snapshot pushed.

**Comment by STRATZ-Ken** [comment]
Does that mean all future data past that time will be removed? Or only in that second?

**Comment by spheenik** [comment]
No, only that single message is incomplete. Rest is completely untouched.

**Comment by STRATZ-Ken** [comment]
Resolved.
