### ISSUE TITLE
Baseline for class CDOTA_Ability_Windrunner_Shackleshot (606) not found

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#235]
Match Id : 5446971749 

```
Sun May 31 12:29:45 PDT 2020 | 5446971749 |  | exception | skadistats.clarity.ClarityException: Baseline for class CDOTA_Ability_Windrunner_Shackleshot (606) not found.
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:480)
	at skadistats.clarity.processor.entities.Entities.processEntityCreate(Entities.java:369)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:317)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by spheenik** [comment]
I suspect corrupt replay.
