### ISSUE TITLE
Halloween Dota Event - No Replays Parse

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#243]
Stack Trace, All replay within the last few hours will crash since new update.
```
Thu Oct 29 19:17:11 EDT 2020 | 5677569404 |  | exception | java.lang.ArrayIndexOutOfBoundsException: 4
	at skadistats.clarity.model.s2.S2LongFieldPathFormat.down(S2LongFieldPathFormat.java:23)
	at skadistats.clarity.model.s2.S2LongModifiableFieldPath.down(S2LongModifiableFieldPath.java:19)
	at skadistats.clarity.decoder.s2.FieldOpType$8.execute(FieldOpType.java:55)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:56)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:14)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:484)
	at skadistats.clarity.processor.entities.Entities.processEntityCreate(Entities.java:369)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:317)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:37)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by spheenik** [comment]
Having a look.

**Comment by spheenik** [comment]
Fixed. Snapshot deploying as we speak.
