### ISSUE TITLE
Dota 7.28 - Bugs

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#247]
```
java.lang.OutOfMemoryError: Java heap space
	at skadistats.clarity.model.state.NestedArrayEntityState$Entry.capacity(NestedArrayEntityState.java:224)
	at skadistats.clarity.decoder.s2.field.VarSubTableField.setValueForFieldPath(VarSubTableField.java:84)
	at skadistats.clarity.decoder.s2.Serializer.setValueForFieldPath(Serializer.java:73)
	at skadistats.clarity.model.state.NestedArrayEntityState.setValueForFieldPath(NestedArrayEntityState.java:93)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:78)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:14)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:486)
	at skadistats.clarity.processor.entities.Entities.processEntityCreate(Entities.java:372)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:317)
	at java.lang.invoke.LambdaForm$DMH/106795967.invokeVirtual_LL_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/336165062.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/2143700734.invokeExact_MT(LambdaForm$MH)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at java.lang.invoke.LambdaForm$DMH/1054764298.invokeVirtual_L3_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/627465465.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/2143700734.invokeExact_MT(LambdaForm$MH)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at java.lang.invoke.LambdaForm$DMH/1054764298.invokeVirtual_L3_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/800541597.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/2143700734.invokeExact_MT(LambdaForm$MH)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

Pretty much every replay does this.  With a very minor few exceptions.

**Comment by STRATZ-Ken** [comment]
Example Match Id : 5746489138

**Comment by howardchung** [comment]
What happens if you increase the Java heap size? Curious to know if it would work if you gave it a ton of memory

**Comment by STRATZ-Ken** [comment]
I tried on my local computer which has 32GB of RAM.  Still happened.

**Comment by spheenik** [comment]
Not sure what exactly is going on, but I did add some code that works around the issue for now.

**Comment by STRATZ-Ken** [comment]
@spheenik 

```
Fri Dec 18 01:16:46 PST 2020 | 5746781946 |  | exception | java.lang.ArrayIndexOutOfBoundsException: 62
	at skadistats.clarity.decoder.bitstream.NormalBitStream64.readUBitInt(NormalBitStream64.java:35)
	at skadistats.clarity.decoder.bitstream.BitStream.readString(BitStream.java:112)
	at skadistats.clarity.decoder.unpacker.StringZeroTerminatedUnpacker.unpack(StringZeroTerminatedUnpacker.java:9)
	at skadistats.clarity.decoder.unpacker.StringZeroTerminatedUnpacker.unpack(StringZeroTerminatedUnpacker.java:5)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:77)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:14)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:486)
	at skadistats.clarity.processor.entities.Entities.processEntityCreate(Entities.java:372)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:317)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Getting some of these now.

**Comment by howardchung** [comment]
Is the new snapshot only available for 2.5 or also for the 2.4 release?

**Comment by spheenik** [comment]
@howardchung  only 2.5 for now.

**Comment by spheenik** [comment]
Update: There's other things changed, I think I know what they are, might have a fix soon.

**Comment by spheenik** [comment]
@STRATZ-Ken @yangex: Pushed a new snapshot that hopefully fixes this.

@howardchung Are you still on 2.4? I can backport this for once to 2.4.3 once it's finished, but I'd advise to switch to 2.5-SNAPSHOT (should work without other code changes)

And generally, I've been asked to switch to semantic versioning, so when we have these 7.28 bugs ironed out, I'll release 2.5.0 and then make minors for every fix.

**Comment by STRATZ-Ken** [comment]
Initial tests of new snapshot have not given an error yet.

**Comment by yangex** [comment]
```
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[na:1.8.0_242]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[na:1.8.0_242]
	at skadistats.clarity.processor.runner.ControllableRunner$1.doLoopControl(ControllableRunner.java:64) ~[Parser.jar:na]
	at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:35) ~[Parser.jar:na]
	at skadistats.clarity.processor.runner.ControllableRunner$LockingLoopController.doLoopControl(ControllableRunner.java:160) ~[Parser.jar:na]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:131) ~[Parser.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[Parser.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[Parser.jar:na]
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[Parser.jar:na]
	at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:238) ~[Parser.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
```
How can I block this？This does not affect the use 
version: 2.5-SNAPSHOT

**Comment by spheenik** [comment]
@yangex not really sure, but this is a different issue. There is a bug somewhere in the ControllableRunner being too verbose in logging why it stopped. Can you share some code that reproduces this in a separate issue?

**Comment by Markxy** [comment]
I am having the same issues, but only on AWS Lambda. Everything is working in local Docker (both 2.4.1 and 2.5-SNAPSHOT).

2.5-SNAPSHOT still has issues with @OnCombatLogEntry in my case (just on Lambda for some reason).
 ```
 java.lang.NullPointerException: null
	at java.lang.String.startsWith(String.java:1405) ~[?:1.8.0_201]
	at java.lang.String.startsWith(String.java:1434) ~[?:1.8.0_201]
	at dotaParser.DemoParser.onCombatLogEntry(DemoParser.java:170) ~[task/:?]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:78) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.runner.AbstractFileRunner.endTicksUntil(AbstractFileRunner.java:44) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.runner.SimpleRunner.lambda$new$0(SimpleRunner.java:18) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:35) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:131) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[clarity-2.5-SNAPSHOT.jar:?]
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33) ~[clarity-2.5-SNAPSHOT.jar:?]
 ```

**Comment by spheenik** [comment]
Seems like you do a `startsWith(null)`.
Can you share lin 170?

**Comment by Markxy** [comment]
@spheenik Didn't notice that, my bad!

This was failing:
```java
@OnCombatLogEntry
public void onCombatLogEntry(CombatLogEntry cle) {
    switch (cle.getType())
        case DOTA_COMBATLOG_DEATH:
            String killer = getAttackerNameCompiled(cle);
            if (killer.startsWith(this.myHeroName)){...}; // line 170
```
The combatlog listener is from the examples combatlog except for the if clause.

And
`this.myHeroName = player.getHeroName();`
where
`Demo.CGameInfo.CDotaGameInfo.CPlayerInfo player`

But isn't it weird that `getAttackerNameCompiled` would return null just in the Lambda environment, where it would run fine locally?

**Comment by spheenik** [comment]
Pretty much...

Here is the code:

https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/combatlog/Main.java#L30-L36

Seems like this can only throw an NPE if `cle` is null, and that's impossible, regarding your code path.

**Comment by Markxy** [comment]
It parsed through some of the demo until it raised that exception. It reached the end of draft and didn't make it to the first creep spawn. Probably when the heroes spawned is when the exception happened.

**Comment by spheenik** [comment]
You'll have to add some debug code to tell me exactly what is null.

**Comment by Markxy** [comment]
@spheenik issue was on my end, apologies!
I had a discrepancy between the input in local vs Lambda. `this.myHeroName` was actually null because that player didn't exist in the demo.

2.5-SNAPSHOT works well. Thank you!
