### ISSUE TITLE
2.5-SNAPSHOT works fine on Mac but not ubuntu

### ISSUE THREAD

**Issue by alex-jin** [skadistats/clarity#249]
I use 2.5-SNAPSHOTto buiild a new project on ubuntu(mvn package). when I parse a DOTA2 rep(match 5751550553), I got below exception. But same code works fine on my Mac. I checked the version of clarity under ~/.m2/repository, which is 2.5-SNAPSHOT. Have any clue? Thanks in advance.

Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface skadistats.clarity.model.FieldPath, but class was expected
	at com.dotamax.parser.Warding.onEntityUpdated(Warding.java:116)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.entities.Entities.emitUpdatedEvent(Entities.java:438)
	at skadistats.clarity.processor.entities.Entities.processEntityUpdate(Entities.java:397)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:330)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at com.dotamax.MainController.run(MainController.java:137)
	at com.dotamax.App.main(App.java:23)

**Comment by alex-jin** [comment]
BTW , 2.4.1 works fine but it takes too much of CPU.

**Comment by alex-jin** [comment]
I ran mvn clean package . problem solved. Thanks for ur project again.
