### ISSUE TITLE
6/23 New Dota Update - Crashing

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#258]
```
Wed Jun 23 16:39:11 PDT 2021 | 6055758770 |  | exception | skadistats.clarity.ClarityException: no decoder for class CDOTATeam at 1/0!
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:73)
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:12)
	at skadistats.clarity.processor.entities.Entities.queueEntityCreate(Entities.java:450)
	at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:397)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:331)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:320)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:160)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Feel free to do any replay that is recent. However 6055758770  should be a quick grab if you need.

**Comment by spheenik** [comment]
Uploading fixed version 2.6.1 to maven central right now.

**Comment by STRATZ-Ken** [comment]
Looks good so far! Thanks for the quick turn around, we really appreciate it.

**Comment by spheenik** [comment]
You're welcome! You guys are my canary in the coalmine. :-)
