### ISSUE TITLE
runner.seek

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#264]
I have some problems using the method “new ControllableRunner(new MappedFileSource(fileName)).runWith(this).seek()"
match_id=6082074457  version 2.6.0.
There is something wrong with this video resource，But I still have problems with using runner.seek(1700).
The client can watch it.
I want to get the Context by runner.getContext()，Skipping selection.
Thank you for your reply
error：
` skadistats.clarity.processor.runner.ControllableRunner$3: Runner thread was terminated by an exception`
`Caused by: skadistats.clarity.ClarityException: no decoder for class CDOTATeam at 1/0!
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:73)
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:12)
	at skadistats.clarity.processor.entities.Entities.queueEntityCreate(Entities.java:450)
	at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:397)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:331)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:320)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:147)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:243)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by BusyLivingDota** [comment]
really? a ControllableRunner? Thats just what I need bro. Thanks!

**Comment by spheenik** [comment]
This issue was fixed in version 2.6.2.
