### ISSUE TITLE
Info For File throwing NoSuchMethodError 

### ISSUE THREAD

**Issue by ChitaAPC** [skadistats/clarity#266]
I've updated to 2.7.0 and am now getting a `NoSuchMethodError` exception when I try and get info from a dem file, here is the relevant bit of the stack trace:

```
Exception in thread "Test_main_runner" java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
	at skadistats.clarity.source.MappedFileSource.setPosition(MappedFileSource.java:42)
	at skadistats.clarity.Clarity.infoForSource(Clarity.java:52)
	at skadistats.clarity.Clarity.infoForFile(Clarity.java:28)
```

**Comment by spheenik** [comment]
Pushed 2.7.1, which will hopefully fix this. Might take an hour until this is available on Maven Central.
