### ISSUE TITLE
CS:GO some maps throw EOFException

### ISSUE THREAD

**Issue by kartol** [skadistats/clarity#267]
Hi,
for some csgo maps, I am unable to parse demofiles.
For example for the first and third map in match https://www.hltv.org/matches/2345224/chaos-vs-rugratz-iem-beijing-haidian-2020-north-america 

It can be reproduced by running gameevent from [clarity-examples](https://github.com/skadistats/clarity-examples) `java -jar target/gameevent.one-jar.jar chaos-vs-rugratz-m1-overpass.dem`

```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.io.EOFException
	at skadistats.clarity.source.MappedFileSource.setPosition(MappedFileSource.java:40)
	at skadistats.clarity.source.Source.skipBytes(Source.java:135)
	at skadistats.clarity.model.engine.CsGoEngineType.readCommandInfo(CsGoEngineType.java:192)
	at skadistats.clarity.model.engine.CsGoEngineType$2.parse(CsGoEngineType.java:217)
	at skadistats.clarity.model.engine.CsGoEngineType$2.parse(CsGoEngineType.java:214)
	at skadistats.clarity.model.engine.CsGoEngineType$1.parse(CsGoEngineType.java:148)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:173)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at skadistats.clarity.examples.gameevent.Main.run(Main.java:21)
	at skadistats.clarity.examples.gameevent.Main.main(Main.java:27)
	... 6 more
```

For the second map, it yields the same exception in a different method of `MappedFileSource`
```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.io.EOFException
	at skadistats.clarity.source.MappedFileSource.readBytes(MappedFileSource.java:56)
	at skadistats.clarity.processor.packet.PacketReader.readFromSource(PacketReader.java:15)
	at skadistats.clarity.model.engine.CsGoEngineType.readPacket(CsGoEngineType.java:184)
	at skadistats.clarity.model.engine.CsGoEngineType.access$200(CsGoEngineType.java:25)
	at skadistats.clarity.model.engine.CsGoEngineType$2.parse(CsGoEngineType.java:221)
	at skadistats.clarity.model.engine.CsGoEngineType$2.parse(CsGoEngineType.java:214)
	at skadistats.clarity.model.engine.CsGoEngineType$1.parse(CsGoEngineType.java:148)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:173)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at skadistats.clarity.examples.gameevent.Main.run(Main.java:21)
	at skadistats.clarity.examples.gameevent.Main.main(Main.java:27)
	... 6 more
```

**Comment by spheenik** [comment]
It is often the case that replays on HLTV are not complete (they are missing a bit of data in the end).
This causes Clarity to correctly throw an EOFException when reaching the end.

I assume that you saying "unable to parse demofiles" is not completely true, since you got valid data up to that point.

Is that correct?

**Comment by kartol** [comment]
Yes, that is correct.
So I will just handle the exception somehow.

Thank you :+1:
