### ISSUE TITLE
Entities ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kartol** [skadistats/clarity#271]
Hi!
I am having trouble to parse first map of https://www.hltv.org/matches/2352464/astralis-vs-godsent-pgl-major-stockholm-2021-challengers-stage

It's crashing on ArrayIndexOutOfBoundsException and can be replicated in clarity-examples with anything using the @UsesEntities annotation.

`java -jar target/entityrun.one-jar.jar ./astralis-vs-godsent-m1-nuke.dem`

```java
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3413
        at skadistats.clarity.model.state.ClientFrame.getEntity(ClientFrame.java:24)
        at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:368)
        at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:331)
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:320)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
        at skadistats.clarity.examples.entityrun.Main.run(Main.java:17)
        at skadistats.clarity.examples.entityrun.Main.main(Main.java:27)
        ... 6 more
```

I found out version `2.4.1` process it without a crash but since `2.5` it's crashing.

Do you know if I am doing something wrong or what could be the cause?

**Comment by spheenik** [comment]
Sorry, forgot to answer earlier.
Seems like the replay is corrupted. Might have a look later.

**Comment by kartol** [comment]
I was also thinking that it might be corrupted.
I am wondering why it's working with the older version of clarity.

**Comment by spheenik** [comment]
Tested again today, works with Version 2.7.5.
