### ISSUE TITLE
Unable to read CDOTAMatchMetadataFile at all?

### ISSUE THREAD

**Issue by hptruong93** [skadistats/clarity#279]
As the title said.
Example match 6449823914.

Code
```
S2DotaMatchMetadata.CDOTAMatchMetadataFile metadata = Clarity.metadataForFile(args[0]);
System.out.println(metadata);
```

Error encountered
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at skadistats.clarity.wire.Packet.parse(Packet.java:36)
	at skadistats.clarity.Clarity.metadataForStream(Clarity.java:76)
	at skadistats.clarity.Clarity.metadataForFile(Clarity.java:65)
	at dota2orbs.orbs.Mappings.main(Mappings.java:161)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at skadistats.clarity.wire.Packet.parse(Packet.java:34)
	... 3 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:174)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:106)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:124)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:129)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at skadistats.clarity.wire.s2.proto.S2DotaMatchMetadata$CDOTAMatchMetadataFile.parseFrom(S2DotaMatchMetadata.java:320)
	... 8 more

At first I thought it's 7.31 but I tried with some old replays and it has the same error.

**Comment by spheenik** [comment]
I did some analysis on MetaDataFiles ages ago, and it never really worked:

https://github.com/skadistats/clarity/issues/165

Maybe the protobufs are outdated as well, so at the moment yes, you can't read this at all. If you could provide a MetaDataFile, I could have a look, but my time is limited at the moment!
