### ISSUE TITLE
New replays parsing issue

### ISSUE THREAD

**Issue by ucontacti** [skadistats/clarity#283]
There seems to be a bug that happens in new replays. Try any new replay (6649464185 match id for instance). The Clarity analyzer and lifestate example both get error:
Clarity analyzer crash:
```
12:20:55.811 ERROR    Runner thread crashed
skadistats.clarity.ClarityException: no decoder for class CDOTATeam at 1/0!
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:73) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:12) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.entities.Entities.queueEntityCreate(Entities.java:450) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:397) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:331) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:320) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.event.Event.raise(Event.java:41) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39) ~[clarity-2.6.0.jar:na]
	at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:243) ~[clarity-2.6.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]
```
Lifestate crash:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: skadistats.clarity.ClarityException: no decoder for class CDOTATeam at 1/0!
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:73)
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:12)
	at skadistats.clarity.processor.entities.Entities.queueEntityCreate(Entities.java:450)
	at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:397)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:331)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:320)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at skadistats.clarity.examples.lifestate.Main.run(Main.java:32)
	at skadistats.clarity.examples.lifestate.Main.main(Main.java:43)
```
In my own code I get crash saying this:
```
Caused by: skadistats.clarity.processor.runner.ControllableRunner$3: Runner thread was terminated by an exception
	at skadistats.clarity.processor.runner.ControllableRunner.waitForTickReached(ControllableRunner.java:294)
	at skadistats.clarity.processor.runner.ControllableRunner.tick(ControllableRunner.java:328)
	at dota2identifier.unit_orders.Main.runControlled(Main.java:262)
	at dota2identifier.unit_orders.Main.main(Main.java:299)
	... 6 more
Caused by: java.lang.IllegalArgumentException: property m_iPlayerID not found on entity of class CDOTAPlayerController
	at skadistats.clarity.model.Entity.getProperty(Entity.java:92)
	at dota2identifier.unit_orders.Main.onMessage(Main.java:191)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.ControllableRunner.lambda$runWith$0(ControllableRunner.java:243)
	at java.lang.Thread.run(Thread.java:748)
```
Again I emphasize that this happens only in new replays.

**Comment by spheenik** [comment]
Hmm, it looks like you use a version of clarity that is not current. The first stack trace says 2.6.0, and there have been fixes since then, that might be needed.

@STRATZ-Ken do you see any issues?

**Comment by spheenik** [comment]
Issue where the error in the first stack trace was fixed: https://github.com/skadistats/clarity/issues/258

**Comment by STRATZ-Ken** [comment]
We have using clarity analyzer all this week (for the love of god, please put a build .jar on the release sections 💯 ).  We didn't notice any crashing.

**Comment by ucontacti** [comment]
I think found the reason for my error. So for new replays (I don't know since when), the "CDOTAPlayer" entity is not created anymore and its new name is "CDOTAPlayerController". Also "m_iPlayerID" property has changed to "m_nPlayerID".
You are right it fixed the issue on the analyzer when I updated the clarity version. It was just a coincidence that this happened in new replays in the analyzer and in my own code. 
I really wish there was somewhere that these changes were documented.
