### ISSUE TITLE
ControllableRunner.seek error or dem has change format

### ISSUE THREAD

**Issue by xiaoyangmoa** [skadistats/clarity#286]
at skadistats.clarity.model.s2.S2LongFieldPathFormat.down(S2LongFieldPathFormat.java:24)
	at skadistats.clarity.model.s2.S2LongModifiableFieldPath.down(S2LongModifiableFieldPath.java:19)
	at skadistats.clarity.io.s2.FieldOpType$15.execute(FieldOpType.java:111)
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:54)
	at skadistats.clarity.io.s2.S2FieldReader.readFields(S2FieldReader.java:12)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:597)
	at skadistats.clarity.processor.entities.Entities.executeEntityCreate(Entities.java:456)
	at skadistats.clarity.processor.entities.Entities.lambda$queueEntityCreate$2(Entities.java:452)
	at java.util.ArrayList.forEach(ArrayList.java:1257)

video id like:
6792847854
6792848069
6792792786
6792799128
6792757290
6792727667

**Comment by spheenik** [comment]
Hi, I fixed it, and am pushing version 2.7.4 to central right now.
See commit https://github.com/skadistats/clarity/commit/212eaddf7dc8b716c22faaec37952236f521a804

**Comment by xiaoyangmoa** [comment]
at skadistats.clarity.model.state.NestedArrayEntityStateIterator.advance(NestedArrayEntityStateIterator.java:41)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:62)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:11)
	at skadistats.clarity.processor.entities.PropertyChange.onEntityCreated(PropertyChange.java:101)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.entities.Entities.emitCreatedEvent(Entities.java:537)
	at skadistats.clarity.processor.entities.Entities.executeEntityCreate(Entities.java:474)
	at skadistats.clarity.processor.entities.Entities.lambda$queueEntityCreate$4(Entities.java:458)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:340)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:332)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
2.7.4 has this problem
