### ISSUE TITLE
Dota Update 10/6/22 Broke all Replays

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#287]
Feel free to use pretty much any match.  Error is OutOfBoundException 5 of size 5.

6792954018
6792953559

**Comment by STRATZ-Ken** [comment]
https://github.com/skadistats/clarity/blob/25cfc0fd96067f36b887839b0afa5798ef215a89/src/main/java/skadistats/clarity/model/s2/S2LongFieldPathFormat.java#L5

I think the issue is on this line.

**Comment by spheenik** [comment]
Fixed, version 2.7.4 released, pushing to central right now, will be available in an hour or so (depending on how fast central is).

**Comment by spheenik** [comment]
see commit https://github.com/skadistats/clarity/commit/212eaddf7dc8b716c22faaec37952236f521a804

**Comment by Noxville** [comment]
Does this break backwards compatibility in any way?

**Comment by spheenik** [comment]
I can't know for sure, but I am pretty sure this is fully backwards-compatible.
It's just that Valve start to encode something new, which uses a bigger field path depth.

**Comment by xiaoyangmoa** [comment]
6793982084 has problem:
at skadistats.clarity.model.state.NestedArrayEntityStateIterator.advance(NestedArrayEntityStateIterator.java:41)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:62)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:11)
	at skadistats.clarity.processor.entities.PropertyChange.onEntityCreated(PropertyChange.java:101)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.entities.Entities.emitCreatedEvent(Entities.java:537)
	at skadistats.clarity.processor.entities.Entities.executeEntityCreate(Entities.java:474)
	at skadistats.clarity.processor.entities.Entities.lambda$queueEntityCreate$4(Entities.java:458)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:340)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:332)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)

**Comment by spheenik** [comment]
Headsup for all: The fix from yesterday was incomplete (and did not work if you are using a ControllableRunner). Fixed in 2.7.5.

**Comment by reacheight** [comment]
Thank you! <3
