### ISSUE TITLE
still can not run: NestedArrayEntityStateIterator.advance(NestedArrayEntityStateIterator.java:41)

### ISSUE THREAD

**Issue by xiaoyangmoa** [skadistats/clarity#288]
ERROR j.l.Package - java.lang.ArrayIndexOutOfBoundsException: 6
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.advance(NestedArrayEntityStateIterator.java:41)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:62)
	at skadistats.clarity.model.state.NestedArrayEntityStateIterator.next(NestedArrayEntityStateIterator.java:11)
	at skadistats.clarity.processor.entities.PropertyChange.onEntityCreated(PropertyChange.java:101)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.entities.Entities.emitCreatedEvent(Entities.java:537)
	at skadistats.clarity.processor.entities.Entities.executeEntityCreate(Entities.java:474)
	at skadistats.clarity.processor.entities.Entities.lambda$queueEntityCreate$4(Entities.java:458)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:340)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:332)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
match is : 6793982084

**Comment by spheenik** [comment]
Fixed in version 2.7.5, released just now.
