### ISSUE TITLE
Unable to parse replay with error "cannot handle game event key type 9"

### ISSUE THREAD

**Issue by hptruong93** [skadistats/clarity#297]
Latest version 2.7.7
Match ID 7048355297

Code:
String f = root + replay + ".dem";
new SimpleRunner(new MappedFileSource(f)).runWith(this);

where "this" is a class with an empty method
@OnCombatLogEntry
public void onCombatLogEntry(CombatLogEntry cle) {
}

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: skadistats.clarity.ClarityException: cannot handle game event key type 9
        at skadistats.clarity.processor.gameevents.GameEvents.onGameEvent(GameEvents.java:110)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)

**Comment by hptruong93** [comment]
Verified this is fixed. Thanks.
