### ISSUE TITLE
Dota 7.33 Out Of Bounds Error

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#299]
All replays are throwing out of bounds errors.  Due to the large amount of changes, not surprised.

**Comment by STRATZ-Ken** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 22128
    at skadistats.clarity.platform.buffer.UnsafeBuffer$B64.get(UnsafeBuffer.java:73)
    at skadistats.clarity.io.bitstream.BitStream64.readUBitInt(BitStream64.java:26)
    at skadistats.clarity.io.bitstream.BitStream64.readBitsIntoByteArray(BitStream64.java:43)
    at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:129)
    at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onCreateStringTable(S2StringTableEmitter.java:63)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
    at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
    at Worker$1.handleDelivery(Worker.java:149)
    at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
    at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by STRATZ-Ken** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: Index 16384 out of bounds for length 16384
    at skadistats.clarity.io.bitstream.BitStream64.readBitsIntoByteArray(BitStream64.java:43)
    at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:123)
    at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onCreateStringTable(S2StringTableEmitter.java:63)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
    at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
    at skadistats.clarity.event.Event.raise(Event.java:41)
    at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
    at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
    at Worker$1.handleDelivery(Worker.java:149)
    at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
    at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by blukai** [comment]
https://github.com/SteamDatabase/GameTracking-Dota2/commit/8851e24f0e3ef0b618e3a60d276a3b0baf88568c#diff-79c9dd229c77c85f462d6d85e29a65f5daf6bf31f199554438d42bd643e89448R405 might be related

**Comment by spheenik** [comment]
Already got it running locally. Fix in a few minutes.

**Comment by spheenik** [comment]
Fix version 2.7.9, pushed to central a minute ago.

**Comment by STRATZ-Ken** [comment]
java.lang.NoSuchMethodError: 'boolean skadistats.clarity.wire.s2.proto.S2NetMessages$CSVCMsg_CreateStringTable.getUsingVarintBitcounts()'
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onCreateStringTable(S2StringTableEmitter.java:51)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at Worker$1.handleDelivery(Worker.java:149)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by STRATZ-Ken** [comment]
Fixed via new Protobufs.
