### ISSUE TITLE
Crash on recent replays

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#311]
Looks like recent replays are breaking the parser when trying to read entities. Sample replay: http://replay272.valve.net/570/7692292009_294475253.dem.bz2

```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 176
        at skadistats.clarity.platform.buffer.UnsafeBuffer$B64.get(UnsafeBuffer.java:73)
        at skadistats.clarity.io.bitstream.BitStream64.readUBitInt(BitStream64.java:26)
        at skadistats.clarity.io.bitstream.BitStream.readUBitVar(BitStream.java:169)
        at skadistats.clarity.io.s2.S2FieldReader.readDeletions(S2FieldReader.java:109)
        at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:432)
        at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:337)
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:332)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
        at skadistats.clarity.event.Event.raise(Event.java:41)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
        at opendota.Parse.<init>(Parse.java:205)
```

**Comment by STRATZ-Ken** [comment]
Yup, pretty much every replay right now is broken.

**Comment by spheenik** [comment]
Why always on a friday?

**Comment by STRATZ-Ken** [comment]
You should be happy it happened on a Thursday.  I missed the TI after party one year because they released Underlord at TI.  I had to go back to the hotel for a few hours to get things moving again :(

**Comment by spheenik** [comment]
Which version of clarity are you guys using?
Seems like odota/parser is still on 2.7.9?

**Comment by spheenik** [comment]
Ok, I'll walk the dog then have a look at the linked replay.
If you guys do not use 3.0.3 then try with that in the meantime.

**Comment by spheenik** [comment]
confirmed not working in 3.0.3

**Comment by spheenik** [comment]
`3.0.4` works around this, by not reading deletions from entity updates any more (for Source 2 / DOTA2)
I just briefly looked at some recent replays, and they all seem to encode 0 deletions. 
Seems like now they stopped encoding the 0, which probably means Valve abandoned the feature.
Not sure though.
