### ISSUE TITLE
Another crash parsing some CS2 demos

### ISSUE THREAD

**Issue by thwonghin** [skadistats/clarity#315]
https://www.hltv.org/matches/2372720/ninjas-in-pyjamas-vs-sashi-yalla-compass-2024

The parser crashes while parsing this demo.

So far I've applied a patch that fixes this [issue](https://github.com/skadistats/clarity/issues/313).
And then another exception raised (I've added some logs for debugging, so the line numbers were shifted a bit):

```
Exception in thread "main" java.io.IOException: invalid embedded packet size: got 124 remaining bits, but size is 224 bits
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:240)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:172)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
```

Interestingly, if I log the size of these problematic messages, they all have `750000` bytes. My speculation is that the messages are getting tuncated or split.

**Comment by spheenik** [comment]
Sure seems like a bug in the CS client recording this.
When you say "these problematic messages", do you have more replays where the same thing occurs?
Can they all be pinned to a certain timespan where they were recorded?

**Comment by thwonghin** [comment]
If I let the parser continue to run without raising exception:

- https://www.hltv.org/matches/2372720/ninjas-in-pyjamas-vs-sashi-yalla-compass-2024
  - The only one demo, happened at at tick 69659, 70253, 71771.
  - Then it failed to parse at tick 71792 with an error `Entity not found for update at index 1408. Entity update cannot be parsed!` 
- https://www.hltv.org/matches/2372733/the-mongolz-vs-ninjas-in-pyjamas-yalla-compass-2024
  - the-mongolz-vs-ninjas-in-pyjamas-m2-mirage.dem, at tick 132277

**Comment by thwonghin** [comment]
Confirmed the demo is broken, it crahsed at that tick (but it worked if I clicked forawrd).
Let me close this.
