### ISSUE TITLE
Index out of Error Bounds

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity#50]
I've been parsing some older replays lately, and I've been hitting this error on a certain range of replays:

```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 107
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:91)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:73)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 107
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:149)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:73)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 12 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 107
	at skadistats.clarity.decoder.BitStream.readNumericBits(BitStream.java:52)
	at skadistats.clarity.decoder.prop.IntDecoder.decode(IntDecoder.java:27)
	at skadistats.clarity.decoder.prop.IntDecoder.decode(IntDecoder.java:7)
	at skadistats.clarity.model.ReceiveProp.decode(ReceiveProp.java:70)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:160)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:103)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:73)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 16 more
```

I've uploaded an example here: https://drive.google.com/file/d/0ByXwOETB_5SZVGU2OFB1SnF2WXc/view?usp=sharing

Any ideas on why this may be the case? I've noticed that I can correctly decode the DtClasses easily, but this errors on parsing Entities.

**Comment by spheenik** [comment]
Strange...
Most certainly a bug.

I'm gonna look into it next week.
(which also happens to be the time to start S2 integration)

**Comment by spheenik** [comment]
Hey man, after thinking about it a second more, I think I know what this is, I deployed a new snapshot, please check if it helps.

**Comment by ykim** [comment]
I just tested it out. It looks like it works :+1:
