### ISSUE TITLE
Game Rules State NoClassDefFoundError

### ISSUE THREAD

**Issue by bwarren2** [skadistats/clarity#60]
Using [this replay](https://www.dropbox.com/s/w8jx0ke5jtm91pz/1837060998_1657195503.dem.bz2?dl=0) (match id 1837060998) and the clarity-examples project with the clarity 2.1 snapshot, I got the below error:

    me@Thoth:~/Projects/clarity-examples$ java -jar target/combatlog.one-jar.jar replay.dem
    Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: skadistats/clarity/model/GameRulesStateType
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:82)
        at skadistats.clarity.examples.combatlog.Main.run(Main.java:151)
        at skadistats.clarity.examples.combatlog.Main.main(Main.java:157)
        ... 6 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: skadistats/clarity/model/GameRulesStateType
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:45)
        at skadistats.clarity.processor.runner.SimpleRunner$1.doLoopControl(SimpleRunner.java:14)
        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:30)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:113)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 9 more
    Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: skadistats/clarity/model/GameRulesStateType
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:94)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 15 more
    Caused by: java.lang.NoClassDefFoundError: skadistats/clarity/model/GameRulesStateType
        at skadistats.clarity.examples.combatlog.Main.onCombatLogEntry(Main.java:115)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 18 more
    Caused by: java.lang.ClassNotFoundException: skadistats.clarity.model.GameRulesStateType
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 21 more

Is there a new addition to the protobufs that needs to be rolled in?

**Comment by spheenik** [comment]
The class has been moved to another package a while ago.
It now is in the package skadistats.clarity.model.s1

It's also not referenced from the combat log example. Is your clarity-examples recent?

**Comment by bwarren2** [comment]
Not recent enough!  Updating fixed it.
