### ISSUE TITLE
IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity#69]
I just received this error on a replay I was parsing:

```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:158)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:226)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 12 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.decodeEntries(S2StringTableEmitter.java:81)
	at skadistats.clarity.processor.stringtables.S2StringTableEmitter.onUpdateStringTable(S2StringTableEmitter.java:58)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 15 more
```

Any ideas why this would be occurring?

**Comment by spheenik** [comment]
As already discussed in IRC, I suspect the replay data to be corrupt :(
