### ISSUE TITLE
Crash in readCombatLogName

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#74]
Looks like it's possible to crash when trying to get the combat log name out of the stringtable:

```
{"url":"http://replay122.valve.net/570/2119235217_1014942462.dem.bz2","state":{"time":{"ellapsed":4.016,"remaining":11.768},"speed":639823.4561752988,"percentage":0.2544276763275405,"size":{"total":10099259,"transferred":2569531}}}
```
```
Exception in thread "main" 
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
        at yasp.Main.run(Main.java:398)
        at yasp.Main.main(Main.java:404)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:44)
        at skadistats.clarity.processor.runner.SimpleRunner$1.doLoopControl(SimpleRunner.java:20)
        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 3 more
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:58)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at skadistats.clarity.model.StringTable.getNameByIndex(StringTable.java:72)
        at skadistats.clarity.model.s2.S2CombatLogEntry.readCombatLogName(S2CombatLogEntry.java:20)
        at skadistats.clarity.model.s2.S2CombatLogEntry.getTargetName(S2CombatLogEntry.java:40)
        at yasp.Main.onCombatLogEntry(Main.java:209)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 12 more
```

**Comment by spheenik** [comment]
Just tried here, works without problems.

Do you have the latest version? I did a fix a few days ago (https://github.com/skadistats/clarity/commit/f9dce8d8ca626fcb17f77732bea63ed6eba9667c) that had exactly this as a topic...

**Comment by howardchung** [comment]
Looks like the snapshot was just pushed?  We pull directly from the version on sonatype when building the image.

https://oss.sonatype.org/#nexus-search;quick~clarity

In any case I haven't seen it again so I'll close it.

**Comment by spheenik** [comment]
I pushed after checking it, because I already suspected I had probably forgotten to do it.
Glad it works now.
Cheers!

**Comment by howardchung** [comment]
Seem to be still be happening.  I mitigated by deleting the job from the parse queue so it doesn't hold up processing.

**Comment by spheenik** [comment]
can you provide the replay?

**Comment by howardchung** [comment]
It's the same one linked above.  I tried rebuilding clarity locally and was able to reproduce it.

**Comment by spheenik** [comment]
Then there must be a problem with your local build process, since that replay is working fine here.
