### ISSUE TITLE
exception after spring cleaning patch

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#82]
Seeing this after the patch:
```
{"url":"http://replay183.valve.net/570/2246977089_1900893527.dem.bz2","state":{"time":{"elapsed":5.832,"remaining":1
00.733},"speed":552098.5939643347,"percentage":0.05472701640599129,"size":{"total":58834543,"transferred":3219839}}}

Exception in thread "main" 
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsE
xception: -1
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
        at yasp.Main.run(Main.java:415)
        at yasp.Main.main(Main.java:421)

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1


        at skadistats.clarity.event.Event.raise(Event.java:25)


        at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:44)


        at skadistats.clarity.processor.runner.SimpleRunner$1.doLoopControl(SimpleRunner.java:20)


        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)


        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)


        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)


        at skadistats.clarity.event.Event.raise(Event.java:23)


        ... 3 more


Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1


        at skadistats.clarity.event.Event.raise(Event.java:25)


        at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:58)


        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)


        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at skadistats.clarity.model.StringTable.getNameByIndex(StringTable.java:72)
        at skadistats.clarity.model.s2.S2CombatLogEntry.readCombatLogName(S2CombatLogEntry.java:20)
        at skadistats.clarity.model.s2.S2CombatLogEntry.getTargetName(S2CombatLogEntry.java:40)
        at yasp.Main.onCombatLogEntry(Main.java:215)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 12 more
```

**Comment by spheenik** [comment]
This is stringtable use before the corresponding entries are there. 

This is what I fixed a month ago, but it never seemed to work on your side...

Unfortunately. I am on vacation without computer. :)

I suspect the entries are there on the next tick. So if you would work around by buffering combat log entries for a tick before you use them it would probably help...

**Comment by howardchung** [comment]
I tried using jitpack.io to build a fresh version from master and am still able to repro locally with the replay above.

After some more trace outputting I see the CombatLogEntry object is as follows:
```
java.lang.ArrayIndexOutOfBoundsException: -1
type: DOTA_COMBATLOG_PLAYERSTATS
target_name: 4294967295
target_source_name: 0
attacker_name: 0
damage_source_name: 0
value: 4294967295
timestamp: 381.16183
stun_duration: 0.0
slow_duration: 0.0
timestamp_raw: 381.40002
last_hits: 0
obs_wards_placed: 0
networth: 0
```

So this appears to be a PLAYERSTATS entry, which we don't currently do anything with.  I will mitigate the issue by try/catching the handler function.  Also target_name appears to be 2^32-1, which is probably going to be an invalid value in the stringtable even if we buffer and retry.

**Comment by spheenik** [comment]
Forgot to push yesterday, but did just now. Happy testing!
