### ISSUE TITLE
Index Out of Bounds

### ISSUE THREAD

**Issue by KenBeanNet** [skadistats/clarity#86]
[pool-3-thread-1] WARN Worker - Wed May 04 08:35:00 EDT 2016 | 2339094637 exception | java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 100
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
	at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:12)
	at Worker$1.handleDelivery(Worker.java:122)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 100
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:44)
	at skadistats.clarity.processor.runner.SimpleRunner$1.doLoopControl(SimpleRunner.java:20)
	at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 100
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:58)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 100
	at skadistats.clarity.model.StringTable.getNameByIndex(StringTable.java:72)
	at skadistats.clarity.model.s2.S2CombatLogEntry.readCombatLogName(S2CombatLogEntry.java:20)
	at skadistats.clarity.model.s2.S2CombatLogEntry.getAttackerName(S2CombatLogEntry.java:60)
	at Parser2.onCombatLogEntry(Parser2.java:476)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 17 more

**Comment by spheenik** [comment]
Will fetch the replay tonight, and see what's happening.

**Comment by KenBeanNet** [comment]
Just so you know, I am running this from two different locations (ISPs) and downloaded the replay multiple times.  It may be something in my parser, but its def crashing. :+1:

**Comment by KenBeanNet** [comment]
Here you go : 

 http://replay156.valve.net/570/2344892981_1565983876.dem.bz2


@OnCombatLogEntry
public void onCombatLogEntry(Context ctx, CombatLogEntry cle) {
if (cle.hasAttackerName() && cle.getAttackerName() != null) {
} 
}

This code will crash this match link above.

**Comment by spheenik** [comment]
Ok, this finally brings some light to the problems that @howardchung had a while ago in #74.

I wrote some test code which demonstrates that the only combat log message type this happens on is DOTA_COMBATLOG_PLAYERSTATS which indeed has an attackerName, but the value is bogus. The indices it refers to will never be set in the string table, not on the next tick or several ticks later, just never.

So this is a "bug" on Valve's side (or rather, an undefined state for the attackerName variable in DOTA_COMBATLOG_PLAYERSTATS. 

I am undecided what to do. I am leaning on returning "UNKNOWN" as a player name in such cases, instead of crashing. 

Any thoughts?

The code:
```java
import com.google.protobuf.ByteString;
import skadistats.clarity.model.CombatLogEntry;
import skadistats.clarity.model.StringTable;
import skadistats.clarity.processor.gameevents.CombatLog;
import skadistats.clarity.processor.gameevents.OnCombatLogEntry;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.processor.stringtables.OnStringTableEntry;
import skadistats.clarity.source.MappedFileSource;

public class Main {

    @OnStringTableEntry(CombatLog.STRING_TABLE_NAME)
    public void onTableEntry(Context ctx, StringTable table, int index, String key, ByteString value) {
        System.out.format("--------------------- set string table %d to %s\n", index, key);
    }

    @OnCombatLogEntry
    public void onCombatLogEntry(Context ctx, CombatLogEntry cle) {
        try {
            if (cle.hasAttackerName()) {
                cle.getAttackerName();
            }
        } catch (Exception e) {
            System.out.println("-- FAIL");
            System.out.println(cle);
            return;
        }
    }

    public static void main(String[] args) throws Exception {
        new SimpleRunner(new MappedFileSource(args[0])).runWith(new Main());
    }
}
```

**Comment by howardchung** [comment]
You should probably return a degenerate value like null or ""
