### ISSUE TITLE
IndexOutOfBoundsExceptions

### ISSUE THREAD

**Issue by wlonk** [skadistats/clarity#87]
With clarity-2.1-SNAPSHOT (from <https://oss.sonatype.org/>), getting this error:

```
        at skadistats.clarity.model.Entity.getPropertyForFieldPath(Entity.java:84)
        at skadistats.clarity.decoder.s2.S2DTClass.getValueForFieldPath(S2DTClass.java:74)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
        at java.util.ArrayList.get(ArrayList.java:429)
        at skadistats.clarity.decoder.s2.field.VarSubTableField.getValueForFieldPath(VarSubTableField.java:68)
        at Parse.getEntityProperty(Parse.java:71)
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at skadistats.clarity.decoder.s2.Serializer.getValueForFieldPath(Serializer.java:70)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:47)
        at Main.run(Main.java:288)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
        at Parse.onTickStart(Parse.java:163)
        at skadistats.clarity.processor.runner.SimpleRunner$1.doLoopControl(SimpleRunner.java:20)
        at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        at Main.parseID(Main.java:147)
        at Parse.run(Parse.java:814)
        at Main.main(Main.java:296)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
```

Am I passing something incorrectly?

**Comment by wlonk** [comment]
Resolved, my own stupidity. Thanks!
