### ISSUE TITLE
Strange null pointer errors happening at inconsistent times.

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#88]
This has been a strange issue I've had for a little while now, but sometimes, and it seems completely random, I get a null pointer exception when I'm performing something on a retrieved property. But the strange thing is, I run again right after the error, and it runs fine... So it doesn't seem to be something in my code. This happens ever 2-3 runs or so, then it crashes, and then the next run doesn't. Here's a snippet of the exception output:

```
Exception in thread "clarity-runner" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
	at skadistats.clarity.processor.runner.ControllableRunner.access$1401(ControllableRunner.java:13)
	at skadistats.clarity.processor.runner.ControllableRunner$3.run(ControllableRunner.java:208)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:49)
	at skadistats.clarity.processor.runner.ControllableRunner$1.doLoopControl(ControllableRunner.java:53)
	at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)
	at skadistats.clarity.processor.runner.ControllableRunner$LockingLoopController.doLoopControl(ControllableRunner.java:168)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 4 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:58)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 11 more
Caused by: java.lang.NullPointerException
        [null pointer location in my code]
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	... 14 more
```

Has this issue ever come up before? I'd be happy to provide some of my code if that will help. It always seems to happen within the OnCombatLogEntry method, with a variable such as cle.getAttackerName, TargetName, InflictorName, etc. showing up as null, when it shouldn't. I say "shouldn't" because it usually doesn't, and runs fine. I don't modify my code at all, I simply run the program, run it again, again, again and then it crashes. So the first few runs it's fine, then randomly crashes. I've never seen this happen and I'm not sure where to begin looking for a solution.

This also may be the reason for the strange behavior with the random empty inventory slots I had in my last issue post, though that was using the Context.

**Comment by spheenik** [comment]
Sorry for the late response, I was away for a few days.

Very interesting issue! I see you are using the controllable runner, so it looks like a synchronization issue. I think I might need more code to look into this, and also, I pushed a new version which cleans the stack traces a lot 12 days ago, If you could update, we'd have concise traces.

Is it possible to isolate a small example that replicates this?

**Comment by TodorovicF** [comment]
Thank you Spheenik. So I think I've isolated the issue. I have a class that runs through a replay until the creeps spawn so I can store the time creeps spawn, along with some other info basic game info. Then in another class I start a new ControllableRunner once the first one is done and halted, and start it from either when creeps spawn or some other point stored by the first basic game info run. But I noticed that when I dumbed it down and removed the first ControllableRunner altogether, the program runs just fine. So the issue seems to come up when using two runners in the same program I think. I'm creating a basic example where the null pointer still happens and I'll send it over soon.

**Comment by TodorovicF** [comment]
So I created two bare classes that simulate what I'm trying to do. One does an initial run of the replay up until a certain point, then halts, then another runner does the full parse of the replay in the main class. Each runner is separated into its own class in NullExample and NullExampleProxy. I set this to run a replay 20 times, and the null pointer exception will usually arise somewhere between runs 2-10 but since it's very random, it can happen later or not at all, so more than one run may be needed. The argument is the same as the clarity examples, just a path to a replay file.

https://gist.github.com/TodorovicF/7a4c15d1b1692b157a0fd6d7a4e619f1
https://gist.github.com/TodorovicF/89ccd304e060843d823c52b1b14de7ff

**Comment by spheenik** [comment]
Very nice test case, thank you!
I had 5 minutes to look over the code, and did not spot the bug yet :)
Unfortunately, I did not have more time the last two evenings, but I will run the code asap.

**Comment by TodorovicF** [comment]
Thank you! I've been able to replicate this behavior on two different computers so I don't know if maybe I'm doing something wrong somewhere else. Thanks for taking a look :)

**Comment by spheenik** [comment]
I finally came around to trying this, and I can run the completely unmodified NullExample without any NPE happening. Tried at least 15 runs, and it'll reliably *not* crash and make all 20 runs.

I am running the example on Linux, with JDK 1.8.0_92-b14 (64 bit). Replay used was 2319964275).
Are you using the latest snapshot?

**Comment by TodorovicF** [comment]
Hmm, I'm on Windows 10 (I hope that's not the issue :( ) and I've tried with JDK 1.7 and 1.8 and I get the same error. Here's the output after running it just now:

```
NullExample Started
Run: 1
Run: 2
Run: 3
Run: 4
Exception in thread "clarity-runner" java.lang.NullPointerException
	at filip.my_dota_project.NullExample.onCombatLog(NullExample.java:59)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	at skadistats.clarity.processor.gameevents.CombatLog.onTickEnd(CombatLog.java:58)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	at skadistats.clarity.processor.runner.AbstractRunner.endTicksUntil(AbstractRunner.java:49)
	at skadistats.clarity.processor.runner.ControllableRunner$1.doLoopControl(ControllableRunner.java:53)
	at skadistats.clarity.processor.runner.LoopController.doLoopControl(LoopController.java:31)
	at skadistats.clarity.processor.runner.ControllableRunner$LockingLoopController.doLoopControl(ControllableRunner.java:168)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:122)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)
	at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:78)
	at skadistats.clarity.processor.runner.ControllableRunner.access$1401(ControllableRunner.java:13)
	at skadistats.clarity.processor.runner.ControllableRunner$3.run(ControllableRunner.java:208)
	at java.lang.Thread.run(Unknown Source)
```

Breaking at:
```
	@OnCombatLogEntry
	public void onCombatLog(Context ctx, CombatLogEntry cle) throws UnsupportedEncodingException {
		// Don't allow the method to run if NullExampleProxy hasn't finished
		if (startRun) {
			if (cle.getType() == DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_MODIFIER_ADD) {
				String buff       = cle.getInflictorName();
				String initiator  = cle.getAttackerName();
				String buffedUnit = cle.getTargetName();
				
				// Null Pointer possible here
				if (buff.contains("foo") &&     <-------- Here
                         ....
```

Now I'm even more confused as to what the problem might be.

**Comment by spheenik** [comment]
Hmm, no updates yet. Maybe my machines are too fast/slow to reproduce it? It really seems like some kind of race condition. Pretty mysterious...

**Comment by spheenik** [comment]
Any updates on this?

**Comment by TodorovicF** [comment]
I still haven't been able to get deeper to the source of the problem, but I have tested it on Linux Ubuntu 16 and the issue doesn't come up, so it seems to be related to a difference in how Windows 10 manages memory versus Linux, I'm just not sure where to go from here with this unfortunately.

**Comment by spheenik** [comment]
I'll close (for cleanup purposes), feel free to reopen if you have another clue.
