### ISSUE TITLE
How debug clarity?

### ISSUE THREAD

**Issue by finist** [skadistats/clarity#90]
Hi, sorry for newbie questions, i am not java developer, but i need debug clarity for some interesting features. I clone clarity repo, and compile it

`````
mvn package
`````

then i clone clarity-examples, and change pom.xml clarity dependency

````
<dependency>
            <groupId>com.skadistats</groupId>
            <artifactId>clarity</artifactId>
            <version>2.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>/users/finist/Projects/clarity/target/clarity-2.1-SNAPSHOT.jar</systemPath>
</dependency>
````

But when i compile and run example

````
mvn -P gameevent package
java -jar target/gameevent.one-jar.jar 1.dem
````

i got

````
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at skadistats.clarity.examples.gameevent.Main.<init>(Main.java:13)
	at skadistats.clarity.examples.gameevent.Main.main(Main.java:28)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
````

**Comment by spheenik** [comment]
The one-jar package does not contain all the required libraries.
I think this has to do with providing clarity via a systemPath. (but I 
am not sure)

Are you using an IDE by chance? Maybe event Intellij Idea?

If so, you can import the clarity-examples into it, and clarity itself 
as a module. That way, your changes to clarity will be immediately 
visible when you re-run something in clarity-examples. Eclipse can do 
the same. Just import both projects as maven projects, and eclipse will 
take care of building correctly.

Am 29.05.2016 um 16:30 schrieb Nikolay Seskin:

**Comment by spheenik** [comment]
Another thing just to get you up and running:

You can just remove the systempath stuff, and do a

mvn install

in clarity whenever you change something in it. The command will install 
your modified version of clarity into your local maven repository. You 
can then do

mvn -P whatever package

in clarity-examples, and it'll use your version of clarity from the 
local repository.

**Comment by finist** [comment]
mvn install works for me, thank you!
